query ListInvoices(
  $businessId: ID!
  $page: Int = 1
  $pageSize: Int = 50
  $status: InvoiceStatus
  $customerId: ID
  $currency: CurrencyCode
  $invoiceDateStart: Date
  $invoiceDateEnd: Date
) {
  business(id: $businessId) {
    invoices(
      page: $page
      pageSize: $pageSize
      status: $status
      customerId: $customerId
      currency: $currency
      invoiceDateStart: $invoiceDateStart
      invoiceDateEnd: $invoiceDateEnd
    ) {
      pageInfo {
        currentPage
        totalPages
        totalCount
      }
      edges {
        node {
          id
          invoiceNumber
          status
          invoiceDate
          dueDate
          customer {
            id
            name
          }
          currency {
            code
          }
          total {
            value
          }
          amountDue {
            value
          }
        }
      }
    }
  }
}

query GetInvoice($businessId: ID!, $invoiceId: ID!) {
  business(id: $businessId) {
    invoice(id: $invoiceId) {
      id
      invoiceNumber
      status
      invoiceDate
      dueDate
      memo
      customer {
        id
        name
        email
      }
      currency {
        code
      }
      items {
        product {
          id
          name
        }
        description
        quantity
        unitPrice
        taxes {
          salesTax {
            id
            name
            rate
          }
          amount {
            value
          }
        }
        subtotal {
          value
        }
        total {
          value
        }
      }
      subtotal {
        value
      }
      taxTotal {
        value
      }
      total {
        value
      }
      amountDue {
        value
      }
      amountPaid {
        value
      }
      pdfUrl
    }
  }
}

mutation InvoiceCreate($input: InvoiceCreateInput!) {
  invoiceCreate(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
    invoice {
      id
      invoiceNumber
      status
      pdfUrl
      total {
        value
      }
      subtotal {
        value
      }
      taxTotal {
        value
      }
    }
  }
}

mutation InvoicePatch($input: InvoicePatchInput!) {
  invoicePatch(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
    invoice {
      id
      status
    }
  }
}

mutation InvoiceSend($input: InvoiceSendInput!) {
  invoiceSend(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
  }
}

mutation InvoiceDelete($input: InvoiceDeleteInput!) {
  invoiceDelete(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
  }
}

mutation InvoiceMarkSent($input: InvoiceMarkSentInput!) {
  invoiceMarkSent(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
  }
}

mutation InvoicePaymentCreateManual($input: InvoicePaymentCreateManualInput!) {
  invoicePaymentCreateManual(input: $input) {
    didSucceed
    inputErrors {
      code
      message
      path
    }
    invoicePayment {
      id
      amount
      paymentDate
      paymentMethod
      memo
    }
  }
}

query ListSalesTaxes($businessId: ID!) {
  business(id: $businessId) {
    salesTaxes {
      edges {
        node {
          id
          name
          abbreviation
          rate
        }
      }
    }
  }
}
