apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-wave
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: mcp-wave
    newName: mcp-wave
    newTag: local
