apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-wave-oauth-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: block-standard
  resources:
    requests:
      storage: 1Gi
